### ISSUE TITLE
 SuluAutomationBundle 2.0 Roadmap

### ISSUE THREAD

**Issue by niklasnatter** [sulu/SuluAutomationBundle#50]
I would really like to release a stable version 2.0 (with Sulu 2.0 compatibility) of this bundle in the near future. Before we do that, we should have a look at the following things:

- [x] Cleanup leftovers from the 1.6 Javascript setup (eg [Gruntfile.js ](https://github.com/sulu/SuluAutomationBundle/blob/2.x/Gruntfile.js)and [package.json](https://github.com/sulu/SuluAutomationBundle/blob/2.x/package.json))
- [x] Check for code that is no longer used in version 2.0 like the [TaskHandlerController](https://github.com/sulu/SuluAutomationBundle/blob/2.x/Controller/TaskHandlerController.php) and remove it
- [x] Adjust form to use a datetime picker instead of two separated pickers for date and time
- [x] Find a solution for https://github.com/sulu/SuluAutomationBundle/issues/51
- [x] Implement a factory for the `AutomationViewBuilder` to keep things consistent with the sulu core: https://github.com/sulu/sulu/pull/6088#discussion_r641394254
- [x] Check permissions in `AutomationAdmin`
- [x] Remove `ListMetadataLoader` + rename list configuration
